/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppBusinessCard {
        "email": string;
        "jobPosition": string;
        "linkedInProfile": string;
        "name": string;
        "phone": string;
        "website": string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface WebCountriesFinder {
        "keyword": string;
    }
}
declare global {
    interface HTMLAppBusinessCardElement extends Components.AppBusinessCard, HTMLStencilElement {
    }
    var HTMLAppBusinessCardElement: {
        prototype: HTMLAppBusinessCardElement;
        new (): HTMLAppBusinessCardElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLWebCountriesFinderElement extends Components.WebCountriesFinder, HTMLStencilElement {
    }
    var HTMLWebCountriesFinderElement: {
        prototype: HTMLWebCountriesFinderElement;
        new (): HTMLWebCountriesFinderElement;
    };
    interface HTMLElementTagNameMap {
        "app-business-card": HTMLAppBusinessCardElement;
        "my-component": HTMLMyComponentElement;
        "web-countries-finder": HTMLWebCountriesFinderElement;
    }
}
declare namespace LocalJSX {
    interface AppBusinessCard {
        "email"?: string;
        "jobPosition"?: string;
        "linkedInProfile"?: string;
        "name"?: string;
        "phone"?: string;
        "website"?: string;
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface WebCountriesFinder {
        "keyword"?: string;
    }
    interface IntrinsicElements {
        "app-business-card": AppBusinessCard;
        "my-component": MyComponent;
        "web-countries-finder": WebCountriesFinder;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-business-card": LocalJSX.AppBusinessCard & JSXBase.HTMLAttributes<HTMLAppBusinessCardElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "web-countries-finder": LocalJSX.WebCountriesFinder & JSXBase.HTMLAttributes<HTMLWebCountriesFinderElement>;
        }
    }
}
